<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReOsuStoryboardPlayer.Core\ReOsuStoryboardPlayer.Core.csproj" />
    <ProjectReference Include="..\ReOsuStoryboardPlayer.WPFControl\ReOsuStoryboardPlayer.WPFControl.csproj" />
    <ProjectReference Include="..\ReOsuStoryboardPlayer\ReOsuStoryboardPlayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>